In [ ]:
print("""
@File         : 0103comparing data from two DataFrames.ipynb
@Author(s)    : Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime  : 2025-06-21 16:28:37
@Email        : cuixuanstephen@gmail.com
@Description  : 
""")

@File         : 0103comparing data from two DataFrames.ipynb
@Author(s)    : Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime  : 2025-06-21 16:28:37
@Email        : cuixuanstephen@gmail.com
@Description  :

In [3]:
import pandas as pd
import random

In [6]:
random.seed(123)

list1 = [['A']*3, ['B']*5, ['C']*7]
charlist = [x for sublist in list1 for x in sublist]
random.shuffle(charlist)
ser1 = pd.Series(charlist)
ser1

0     C
1     B
2     C
3     B
4     A
5     B
6     C
7     C
8     C
9     C
10    C
11    B
12    A
13    B
14    A
dtype: object

In [7]:
random.seed(123)
ser2 = pd.Series(random.sample(range(10, 100), 15))
ser2

0     16
1     44
2     21
3     62
4     23
5     14
6     58
7     78
8     81
9     52
10    53
11    30
12    27
13    99
14    41
dtype: int64

In [9]:
prod_df1 = pd.concat([ser1, ser2], axis='columns')
prod_df1.columns = ['Product', 'Sales']
prod_df1.head(5)

  Product  Sales
0       C     16
1       B     44
2       C     21
3       B     62
4       A     23

In [10]:
random.seed(321)
list1 = [['A']*2, ['B']*8, ['C']*5]
charlist = [x for sublist in list1 for x in sublist]
random.shuffle(charlist)
ser3 = pd.Series(charlist)

In [11]:
random.seed(321)
ser4 = pd.Series(random.sample(range(10, 100), 15))
ser4.head()

0    45
1    60
2    26
3    57
4    81
dtype: int64

In [12]:
prod_df2 = pd.concat([ser3, ser4], axis='columns')
prod_df2.columns = ['Product', 'Sales']
prod_df2.head(5)

  Product  Sales
0       C     45
1       A     60
2       A     26
3       C     57
4       C     81

In [13]:
prod_df2['Sales'].eq(45)

0      True
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
Name: Sales, dtype: bool

In [14]:
prod_df2[prod_df2['Sales'].eq(45)]

  Product  Sales
0       C     45

In [15]:
prod_df2['Sales'].gt(prod_df1['Sales'])

0      True
1      True
2      True
3     False
4      True
5      True
6     False
7     False
8      True
9      True
10     True
11     True
12     True
13    False
14     True
Name: Sales, dtype: bool

In [16]:
prod_df2[prod_df2['Sales'].gt(prod_df1['Sales'])]

   Product  Sales
0        C     45
1        A     60
2        A     26
4        C     81
5        B     66
8        C     87
9        B     68
10       B     64
11       B     95
12       B     38
14       B     75

In [17]:
prod_df2[prod_df2['Sales'].lt(prod_df1['Sales'])]

   Product  Sales
3        C     57
6        C     53
7        B     41
13       B     11

In [18]:
prod_df2.iloc[[2, 5, 6, 8]]

  Product  Sales
2       A     26
5       B     66
6       C     53
8       C     87

In [20]:
tab1 = prod_df1.groupby(['Product']).agg('sum')
tab2 = prod_df2.groupby(['Product']).agg('sum')

In [21]:
tab1

         Sales
Product
A           91
B          249
C          359

In [22]:
tab2

         Sales
Product
A           86
B          458
C          323

In [24]:
tab3 = pd.merge(tab1, tab2, on=['Product'])
tab3

         Sales_x  Sales_y
Product
A             91       86
B            249      458
C            359      323

In [25]:
tab3.columns = ['Sales1', 'Sales2']
tab3

         Sales1  Sales2
Product
A            91      86
B           249     458
C           359     323