In [2]:
print("""
@File         : pd.wide_to_long.ipynb
@Author(s)    : Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime  : 2025-01-03 22:50:18
@Email        : cuixuanstephen@gmail.com
@Description  : pd.wide_to_long
""")

@File         : pd.wide_to_long.ipynb
@Author(s)    : Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime  : 2025-01-03 22:50:18
@Email        : cuixuanstephen@gmail.com
@Description  : pd.wide_to_long

In [3]:
import pandas as pd

pandas 还提供了 `pd.wide_to_long` 函数，它可以帮助你进行转换，如果你的字段遵循特定的命名模式。

In [4]:
df = pd.DataFrame([
    ["Widget 1", 1, 2, 4, 8],
    ["Widget 2", 16, 32, 64, 128],
], columns=["widget", "quarter_1", "quarter_2", "quarter_3", "quarter_4"])
df = df.convert_dtypes(dtype_backend="numpy_nullable")

df

     widget  quarter_1  quarter_2  quarter_3  quarter_4
0  Widget 1          1          2          4          8
1  Widget 2         16         32         64        128

In [8]:
df.set_index('widget').stack().reset_index().rename(
    columns={'level_1': 'quarter', 0: 'quantity'}
)

     widget    quarter  quantity
0  Widget 1  quarter_1         1
1  Widget 1  quarter_2         2
2  Widget 1  quarter_3         4
3  Widget 1  quarter_4         8
4  Widget 2  quarter_1        16
5  Widget 2  quarter_2        32
6  Widget 2  quarter_3        64
7  Widget 2  quarter_4       128

In [11]:
df.melt(
    id_vars='widget', var_name='quarter', value_name='quantity'
)

     widget    quarter  quantity
0  Widget 1  quarter_1         1
1  Widget 2  quarter_1        16
2  Widget 1  quarter_2         2
3  Widget 2  quarter_2        32
4  Widget 1  quarter_3         4
5  Widget 2  quarter_3        64
6  Widget 1  quarter_4         8
7  Widget 2  quarter_4       128

In [17]:
pd.wide_to_long(df, 
                i=['widget'], stubnames='quarter_', 
                j='quarter').reset_index().rename(columns={'quarter_': 'quantity'})

     widget  quarter  quantity
0  Widget 1        1         1
1  Widget 2        1        16
2  Widget 1        2         2
3  Widget 2        2        32
4  Widget 1        3         4
5  Widget 2        3        64
6  Widget 1        4         8
7  Widget 2        4       128